Add exit 1 to create-release

diff --git a/.github/workflows/create-release.yml b/.github/workflows/create-release.yml
--- a/.github/workflows/create-release.yml
+++ b/.github/workflows/create-release.yml
@@ -58,4 +58,5 @@ jobs:
 #          token: ${{ secrets.GITHUB_TOKEN }}
       - name: Test create-release
         run: |
-          echo "::error::An error occurred while create-release"
+          echo "::error::An error occurred while create-release" 
+          exit 1
